on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Test
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test

      - name: Upload coverage
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          
